#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libvarlink
Version  : 18
Release  : 2
URL      : https://github.com/varlink/libvarlink/archive/18/libvarlink-18.tar.gz
Source0  : https://github.com/varlink/libvarlink/archive/18/libvarlink-18.tar.gz
Summary  : Varlink C Library
Group    : Development/Tools
License  : Apache-2.0
Requires: libvarlink-bin = %{version}-%{release}
Requires: libvarlink-data = %{version}-%{release}
Requires: libvarlink-lib = %{version}-%{release}
Requires: libvarlink-license = %{version}-%{release}
BuildRequires : buildreq-meson

%description
Varlink C Library

%package bin
Summary: bin components for the libvarlink package.
Group: Binaries
Requires: libvarlink-data = %{version}-%{release}
Requires: libvarlink-license = %{version}-%{release}

%description bin
bin components for the libvarlink package.


%package data
Summary: data components for the libvarlink package.
Group: Data

%description data
data components for the libvarlink package.


%package dev
Summary: dev components for the libvarlink package.
Group: Development
Requires: libvarlink-lib = %{version}-%{release}
Requires: libvarlink-bin = %{version}-%{release}
Requires: libvarlink-data = %{version}-%{release}
Provides: libvarlink-devel = %{version}-%{release}
Requires: libvarlink = %{version}-%{release}

%description dev
dev components for the libvarlink package.


%package lib
Summary: lib components for the libvarlink package.
Group: Libraries
Requires: libvarlink-data = %{version}-%{release}
Requires: libvarlink-license = %{version}-%{release}

%description lib
lib components for the libvarlink package.


%package license
Summary: license components for the libvarlink package.
Group: Default

%description license
license components for the libvarlink package.


%prep
%setup -q -n libvarlink-18
cd %{_builddir}/libvarlink-18

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579204169
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libvarlink
cp %{_builddir}/libvarlink-18/LICENSE %{buildroot}/usr/share/package-licenses/libvarlink/92170cdc034b2ff819323ff670d3b7266c8bffcd
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/varlink

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/varlink
/usr/share/vim/vimfiles/after/ftdetect/varlink.vim
/usr/share/vim/vimfiles/after/ftplugin/varlink.vim
/usr/share/vim/vimfiles/after/syntax/varlink.vim

%files dev
%defattr(-,root,root,-)
/usr/include/varlink.h
/usr/lib64/libvarlink.so
/usr/lib64/pkgconfig/libvarlink.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libvarlink.so.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libvarlink/92170cdc034b2ff819323ff670d3b7266c8bffcd
